//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        public int codigo_empleado { get; set; }
        public string Nombre { get; set; }
        public decimal Horas_laboradas { get; set; }
        public decimal Salario_Hora { get; set; }
        public decimal Salario_Bruto { get; set; }
    }
}
